# Generated by Django 5.2.1 on 2025-06-04 09:58

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='invite_code',
            field=models.CharField(default=api.models.generate_invite_code, editable=False, max_length=8),
        ),
    ]
