# Generated by Django 5.2.1 on 2025-06-04 10:01

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_fill_invite_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='invite_code',
            field=models.CharField(default=api.models.generate_invite_code, editable=False, max_length=8, unique=True),
        ),
    ]
