# Generated by Django 5.2.1 on 2025-06-13 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pending_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
